require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*

Layout/ExtraSpacing:
  Exclude:
    - config/**/*

Layout/LineLength:
  Max: 95

Layout/SpaceAroundOperators:
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFetchBlock:
  Exclude:
    - config/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - config/**/*

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/acceptance/**/*.rb

# Buggy cop
RSpec/FactoryBot/CreateList:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/acceptance/**/*.rb
