require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - config/**/*

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/acceptance/**/*.rb
