default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "#{Rails.root.basename}_dev") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "#{Rails.root.basename}_test") %>

production:
  <<: *default
