name: Ruby

on: [push]

env:
  POSTGRES_HOST: localhost
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  RAILS_ENV: test

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: Code style
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
      - name: Cache bundle
        uses: actions/cache@v1
        with:
          path: .bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Install Gems
        run: |
          gem install bundler
          bundle install --path .bundle --jobs 4
      - name: Check code
        run: bin/rubocop
  rspec:
    runs-on: ubuntu-latest
    name: Tests
    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env: ${{ env }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
      - name: Cache bundle
        uses: actions/cache@v1
        with:
          path: .bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          gem install bundler
          bundle install --path .bundle --jobs 4
      - name: Migrate database
        run: |
          cp .env.example .env
          bin/rails db:setup
      - name: Run tests
        run: bin/rspec
